/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eigenes Profil */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Profil ändern */
        patch: operations["patch_me_api_me_patch"];
        trace?: never;
    };
    "/api/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Einstellungen (wirksam und gespeichert) */
        get: operations["get_settings__api_me_settings_get"];
        /** Einstellungen ersetzen */
        put: operations["put_settings_api_me_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle Zielversionen, neueste zuerst */
        get: operations["list_goals_api_me_goals_get"];
        put?: never;
        /** Neue Zielversion */
        post: operations["create_goal_api_me_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/goals/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zielversion, die an einem Tag gilt */
        get: operations["active_goal_api_me_goals_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/supplements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supplemente: Liste */
        get: operations["list_items_api_me_supplements_get"];
        put?: never;
        /** Supplemente: Anlegen */
        post: operations["create_item_api_me_supplements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/supplements/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supplemente: Einzeln lesen */
        get: operations["get_item_api_me_supplements__item_id__get"];
        /** Supplemente: Ersetzen */
        put: operations["replace_item_api_me_supplements__item_id__put"];
        post?: never;
        /** Supplemente: Löschen */
        delete: operations["delete_item_api_me_supplements__item_id__delete"];
        options?: never;
        head?: never;
        /** Supplemente: Teilweise ändern */
        patch: operations["patch_item_api_me_supplements__item_id__patch"];
        trace?: never;
    };
    "/api/me/nutrient-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ernährungsregeln: Liste */
        get: operations["list_items_api_me_nutrient_rules_get"];
        put?: never;
        /** Ernährungsregeln: Anlegen */
        post: operations["create_item_api_me_nutrient_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/nutrient-rules/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ernährungsregeln: Einzeln lesen */
        get: operations["get_item_api_me_nutrient_rules__item_id__get"];
        /** Ernährungsregeln: Ersetzen */
        put: operations["replace_item_api_me_nutrient_rules__item_id__put"];
        post?: never;
        /** Ernährungsregeln: Löschen */
        delete: operations["delete_item_api_me_nutrient_rules__item_id__delete"];
        options?: never;
        head?: never;
        /** Ernährungsregeln: Teilweise ändern */
        patch: operations["patch_item_api_me_nutrient_rules__item_id__patch"];
        trace?: never;
    };
    "/api/me/training-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trainingsplan: Liste */
        get: operations["list_items_api_me_training_plan_get"];
        put?: never;
        /** Trainingsplan: Anlegen */
        post: operations["create_item_api_me_training_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/training-plan/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trainingsplan: Einzeln lesen */
        get: operations["get_item_api_me_training_plan__item_id__get"];
        /** Trainingsplan: Ersetzen */
        put: operations["replace_item_api_me_training_plan__item_id__put"];
        post?: never;
        /** Trainingsplan: Löschen */
        delete: operations["delete_item_api_me_training_plan__item_id__delete"];
        options?: never;
        head?: never;
        /** Trainingsplan: Teilweise ändern */
        patch: operations["patch_item_api_me_training_plan__item_id__patch"];
        trace?: never;
    };
    "/api/me/lab-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laborregeln: Liste */
        get: operations["list_items_api_me_lab_rules_get"];
        put?: never;
        /** Laborregeln: Anlegen */
        post: operations["create_item_api_me_lab_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/lab-rules/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laborregeln: Einzeln lesen */
        get: operations["get_item_api_me_lab_rules__item_id__get"];
        /** Laborregeln: Ersetzen */
        put: operations["replace_item_api_me_lab_rules__item_id__put"];
        post?: never;
        /** Laborregeln: Löschen */
        delete: operations["delete_item_api_me_lab_rules__item_id__delete"];
        options?: never;
        head?: never;
        /** Laborregeln: Teilweise ändern */
        patch: operations["patch_item_api_me_lab_rules__item_id__patch"];
        trace?: never;
    };
    "/api/me/imports/hae": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Health-Auto-Export-Datei importieren (.zip oder .csv) */
        post: operations["import_hae_api_me_imports_hae_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/imports/apple-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apple-Health-Export importieren (export.zip oder export.xml) */
        post: operations["import_apple_health_api_me_imports_apple_health_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/imports/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Laborbefund importieren (.pdf) */
        post: operations["import_labs_api_me_imports_labs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Letzte Importe (neueste zuerst, max. 20) */
        get: operations["list_imports_api_me_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/imports/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status eines Imports */
        get: operations["get_import_api_me_imports__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/health/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tageswerte (aufsteigend nach Datum)
         * @description Ohne `source`: je Tag aus allen Quellen zusammengeführt, je Feld gewinnt die Quelle mit der höchsten Priorität aus den Einstellungen (`source_priority`). Mit `source`: nur die Rohzeilen dieser Quelle.
         */
        get: operations["get_daily_api_me_health_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workouts (neueste zuerst)
         * @description Alle gespeicherten Workouts, auch wenn zwei Quellen dasselbe Training liefern (`source`).
         */
        get: operations["get_workouts_api_me_workouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Laborberichte mit Ergebnissen (neueste zuerst)
         * @description Mit `flagged=true` nur Ergebnisse mit Kennzeichen L/H, mit `pending=true` nur ausstehende. Werden beide gesetzt, zählt, was mindestens eines davon erfüllt. Berichte ohne passende Ergebnisse entfallen.
         */
        get: operations["list_labs_api_me_labs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/labs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jüngster Wert je Analyt
         * @description Je Analyt der neueste nicht ausstehende Wert über alle Berichte, mit Datum und Referenz.
         */
        get: operations["latest_labs_api_me_labs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/labs/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ein Laborbericht */
        get: operations["get_lab_api_me_labs__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Übersicht
         * @description Gewicht und Trend, mittlere Energie, Workouts der letzten 8 Wochen, Datenabdeckung je Quelle, Laborstand und letzte Importe. Ohne Daten sind Werte `null` bzw. Listen leer.
         */
        get: operations["get_dashboard_api_me_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tagesziel inkl. Mahlzeiten-Verteilung */
        get: operations["get_targets_api_me_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/health/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gewicht/Körperfett von Hand eintragen */
        post: operations["add_manual_measurement_api_me_health_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health-Check */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spike/shopping-list.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SPIKE: Beispiel-Einkaufsliste (wird in Phase 4 ersetzt)
         * @description SPIKE-DATEN: fest hinterlegte Beispiel-Einkaufsliste zum Testen des Apple Shortcuts. Dieser Endpoint wird in Phase 4 durch die echte, aus dem Wochenplan generierte Einkaufsliste ersetzt und ist nicht stabil.
         */
        get: operations["spike_shopping_list_api_spike_shopping_list_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BodyOut */
        BodyOut: {
            /** Weight Kg */
            weight_kg: number;
            /**
             * Weight Date
             * Format: date
             */
            weight_date: string;
            /** Body Fat Pct */
            body_fat_pct: number | null;
            /** Lean Mass Kg */
            lean_mass_kg: number | null;
            /** Height Cm */
            height_cm: number;
            /** Age Years */
            age_years: number;
        };
        /** Body_import_apple_health_api_me_imports_apple_health_post */
        Body_import_apple_health_api_me_imports_apple_health_post: {
            /**
             * File
             * @description Die Datei als Multipart-Feld `file`.
             */
            file: string;
        };
        /** Body_import_hae_api_me_imports_hae_post */
        Body_import_hae_api_me_imports_hae_post: {
            /**
             * File
             * @description Die Datei als Multipart-Feld `file`.
             */
            file: string;
        };
        /** Body_import_labs_api_me_imports_labs_post */
        Body_import_labs_api_me_imports_labs_post: {
            /**
             * File
             * @description Die Datei als Multipart-Feld `file`.
             */
            file: string;
        };
        /**
         * DailyOut
         * @description Tageswerte. Einheiten: kg, Prozent 0-100, kcal, Schritte, Schläge/min, ms, Stunden.
         */
        DailyOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Lean Mass Kg */
            lean_mass_kg?: number | null;
            /** Active Kcal */
            active_kcal?: number | null;
            /** Basal Kcal */
            basal_kcal?: number | null;
            /** Steps */
            steps?: number | null;
            /** Resting Hr */
            resting_hr?: number | null;
            /** Hrv Ms */
            hrv_ms?: number | null;
            /** Sleep H */
            sleep_h?: number | null;
        };
        /** DashboardOut */
        DashboardOut: {
            weight: components["schemas"]["WeightOut"];
            energy: components["schemas"]["EnergyOut"];
            /** Workouts */
            workouts: components["schemas"]["WorkoutWeekOut"][];
            /** Data */
            data: components["schemas"]["SourceCoverageOut"][];
            labs: components["schemas"]["LabsSummaryOut"];
            /** Imports */
            imports: components["schemas"]["ImportJobOut"][];
        };
        /**
         * EnergyOut
         * @description Mittel über die letzten 28 Tage mit vollständigen Gerätedaten (Ruhe und aktiv).
         */
        EnergyOut: {
            /** Avg Active Kcal */
            avg_active_kcal: number | null;
            /** Avg Basal Kcal */
            avg_basal_kcal: number | null;
            /** Device Tdee Kcal */
            device_tdee_kcal: number | null;
            /** N Days */
            n_days: number;
            /** Coverage */
            coverage: number;
            /** Last Day */
            last_day: string | null;
        };
        /** GoalIn */
        GoalIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "lose" | "maintain" | "gain";
            /** Rate Kg Per Week */
            rate_kg_per_week?: number | null;
            /** Kcal Modifier Pct */
            kcal_modifier_pct?: number | null;
            /** Protein G Per Kg */
            protein_g_per_kg?: number | null;
            /** Fat Pct */
            fat_pct?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportJobOut
         * @description Stand eines Import-Jobs.
         */
        ImportJobOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Filename */
            filename: string | null;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Message */
            message: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** LabReportOut */
        LabReportOut: {
            /** Id */
            id: number;
            /** Order No */
            order_no: string | null;
            /** Lab Name */
            lab_name: string | null;
            /** Report Type */
            report_type: string;
            /** Sample Datetime */
            sample_datetime: string | null;
            /** Source Filename */
            source_filename: string | null;
            /** Created At */
            created_at: string | null;
            /** Results */
            results: components["schemas"]["LabResultOut"][];
        };
        /**
         * LabResultOut
         * @description Ein Laborwert. `value_op` ("<" oder ">") gilt für den Messwert, `ref_op` für einseitige Referenzen.
         */
        LabResultOut: {
            /** Id */
            id: number;
            /** Analyte */
            analyte: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
            /** Value Op */
            value_op: string | null;
            /** Flag */
            flag: string | null;
            /** Ref Low */
            ref_low: number | null;
            /** Ref High */
            ref_high: number | null;
            /** Ref Op */
            ref_op: string | null;
            /** Pending */
            pending: boolean;
            /** Method */
            method: string | null;
            /** Material */
            material: string | null;
        };
        /** LabRuleIn */
        LabRuleIn: {
            /** Name */
            name: string;
            /** Analyte */
            analyte: string;
            /**
             * Comparator
             * @enum {string}
             */
            comparator: "lt" | "gt" | "between" | "outside_ref";
            /** Threshold Low */
            threshold_low?: number | null;
            /** Threshold High */
            threshold_high?: number | null;
            /** Effect Key */
            effect_key: string;
            /**
             * Effect Weight
             * @default 0.5
             */
            effect_weight: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Doctor Confirmed
             * @default false
             */
            doctor_confirmed: boolean;
            /**
             * Suggested By App
             * @default false
             */
            suggested_by_app: boolean;
            /** Source */
            source?: string | null;
            /** Note */
            note?: string | null;
        };
        /** LabRuleInPatch */
        LabRuleInPatch: {
            /** Name */
            name?: string | null;
            /** Analyte */
            analyte?: string | null;
            /** Comparator */
            comparator?: ("lt" | "gt" | "between" | "outside_ref") | null;
            /** Threshold Low */
            threshold_low?: number | null;
            /** Threshold High */
            threshold_high?: number | null;
            /** Effect Key */
            effect_key?: string | null;
            /** Effect Weight */
            effect_weight?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Doctor Confirmed */
            doctor_confirmed?: boolean | null;
            /** Suggested By App */
            suggested_by_app?: boolean | null;
            /** Source */
            source?: string | null;
            /** Note */
            note?: string | null;
        };
        /** LabRuleOut */
        LabRuleOut: {
            /** Name */
            name: string;
            /** Analyte */
            analyte: string;
            /**
             * Comparator
             * @enum {string}
             */
            comparator: "lt" | "gt" | "between" | "outside_ref";
            /** Threshold Low */
            threshold_low?: number | null;
            /** Threshold High */
            threshold_high?: number | null;
            /** Effect Key */
            effect_key: string;
            /**
             * Effect Weight
             * @default 0.5
             */
            effect_weight: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Doctor Confirmed
             * @default false
             */
            doctor_confirmed: boolean;
            /**
             * Suggested By App
             * @default false
             */
            suggested_by_app: boolean;
            /** Source */
            source?: string | null;
            /** Note */
            note?: string | null;
            /** Id */
            id: number;
        };
        /** LabsSummaryOut */
        LabsSummaryOut: {
            /** Latest Report Date */
            latest_report_date: string | null;
            /** Latest Report Type */
            latest_report_type: string | null;
            /** Flagged Count */
            flagged_count: number;
            /** Pending Count */
            pending_count: number;
        };
        /**
         * LatestLabValueOut
         * @description Jüngster vorhandener Wert eines Analyten über alle Berichte.
         */
        LatestLabValueOut: {
            /** Analyte */
            analyte: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
            /** Value Op */
            value_op: string | null;
            /** Flag */
            flag: string | null;
            /** Ref Low */
            ref_low: number | null;
            /** Ref High */
            ref_high: number | null;
            /** Ref Op */
            ref_op: string | null;
            /** Report Id */
            report_id: number;
            /** Report Date */
            report_date: string | null;
        };
        /** MacroOut */
        MacroOut: {
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Carb G */
            carb_g: number;
        };
        /** ManualMeasurementIn */
        ManualMeasurementIn: {
            /**
             * Day
             * @description Datum, Standard: heute
             */
            day?: string | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Lean Mass Kg */
            lean_mass_kg?: number | null;
        };
        /** ManualMeasurementOut */
        ManualMeasurementOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Weight Kg */
            weight_kg: number | null;
            /** Body Fat Pct */
            body_fat_pct: number | null;
            /** Lean Mass Kg */
            lean_mass_kg: number | null;
        };
        /** NutrientRuleIn */
        NutrientRuleIn: {
            /** Subject */
            subject: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "max" | "min" | "avoid" | "target";
            /** Value */
            value?: number | null;
            /** Unit */
            unit?: string | null;
            /**
             * Per
             * @default day
             * @enum {string}
             */
            per: "day" | "week";
            /**
             * Hard
             * @default true
             */
            hard: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Doctor Confirmed
             * @default false
             */
            doctor_confirmed: boolean;
            /**
             * Suggested By App
             * @default false
             */
            suggested_by_app: boolean;
            /** Source */
            source?: string | null;
            /** Note */
            note?: string | null;
        };
        /** NutrientRuleInPatch */
        NutrientRuleInPatch: {
            /** Subject */
            subject?: string | null;
            /** Kind */
            kind?: ("max" | "min" | "avoid" | "target") | null;
            /** Value */
            value?: number | null;
            /** Unit */
            unit?: string | null;
            /** Per */
            per?: ("day" | "week") | null;
            /** Hard */
            hard?: boolean | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Doctor Confirmed */
            doctor_confirmed?: boolean | null;
            /** Suggested By App */
            suggested_by_app?: boolean | null;
            /** Source */
            source?: string | null;
            /** Note */
            note?: string | null;
        };
        /** NutrientRuleOut */
        NutrientRuleOut: {
            /** Subject */
            subject: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "max" | "min" | "avoid" | "target";
            /** Value */
            value?: number | null;
            /** Unit */
            unit?: string | null;
            /**
             * Per
             * @default day
             * @enum {string}
             */
            per: "day" | "week";
            /**
             * Hard
             * @default true
             */
            hard: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Doctor Confirmed
             * @default false
             */
            doctor_confirmed: boolean;
            /**
             * Suggested By App
             * @default false
             */
            suggested_by_app: boolean;
            /** Source */
            source?: string | null;
            /** Note */
            note?: string | null;
            /** Id */
            id: number;
        };
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Sex
             * @enum {string}
             */
            sex: "m" | "f";
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Height Cm */
            height_cm: number | null;
        };
        /** PersonPatch */
        PersonPatch: {
            /** Name */
            name?: string | null;
            /** Sex */
            sex?: ("m" | "f") | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Height Cm */
            height_cm?: number | null;
        };
        /**
         * PersonSettings
         * @description Alle einstellbaren Werte einer Person. Fehlende Felder = sichere Standardwerte.
         */
        PersonSettings: {
            /** Kcal Floor */
            kcal_floor?: number | null;
            /**
             * Protein Floor G Per Kg
             * @default 1.2
             */
            protein_floor_g_per_kg: number;
            /** Max Rate Kg Per Week */
            max_rate_kg_per_week?: number | null;
            /** Weight Floor Kg */
            weight_floor_kg?: number | null;
            /** Bf Floor Pct */
            bf_floor_pct?: number | null;
            /**
             * Taper Weight Kg
             * @default 3
             */
            taper_weight_kg: number;
            /**
             * Taper Bf Pct Points
             * @default 2
             */
            taper_bf_pct_points: number;
            /**
             * Kcal Per Kg
             * @default 7700
             */
            kcal_per_kg: number;
            /**
             * Use Katch Mcardle
             * @default false
             */
            use_katch_mcardle: boolean;
            /**
             * Tdee Calibration
             * @default true
             */
            tdee_calibration: boolean;
            /** Reported Intake Kcal */
            reported_intake_kcal?: number | null;
            /** Day Type Weights */
            day_type_weights?: {
                [key: string]: number;
            };
            /** Slot Shares */
            slot_shares?: {
                [key: string]: number;
            };
            /** Slot Shares Weekend */
            slot_shares_weekend?: {
                [key: string]: number;
            } | null;
            /** Single Meal Max Kcal */
            single_meal_max_kcal?: number | null;
            /** Source Priority */
            source_priority?: string[];
        };
        /**
         * SettingsIn
         * @description Wie `PersonSettings`, aber unbekannte Felder führen zu 422.
         */
        SettingsIn: {
            /** Kcal Floor */
            kcal_floor?: number | null;
            /**
             * Protein Floor G Per Kg
             * @default 1.2
             */
            protein_floor_g_per_kg: number;
            /** Max Rate Kg Per Week */
            max_rate_kg_per_week?: number | null;
            /** Weight Floor Kg */
            weight_floor_kg?: number | null;
            /** Bf Floor Pct */
            bf_floor_pct?: number | null;
            /**
             * Taper Weight Kg
             * @default 3
             */
            taper_weight_kg: number;
            /**
             * Taper Bf Pct Points
             * @default 2
             */
            taper_bf_pct_points: number;
            /**
             * Kcal Per Kg
             * @default 7700
             */
            kcal_per_kg: number;
            /**
             * Use Katch Mcardle
             * @default false
             */
            use_katch_mcardle: boolean;
            /**
             * Tdee Calibration
             * @default true
             */
            tdee_calibration: boolean;
            /** Reported Intake Kcal */
            reported_intake_kcal?: number | null;
            /** Day Type Weights */
            day_type_weights?: {
                [key: string]: number;
            };
            /** Slot Shares */
            slot_shares?: {
                [key: string]: number;
            };
            /** Slot Shares Weekend */
            slot_shares_weekend?: {
                [key: string]: number;
            } | null;
            /** Single Meal Max Kcal */
            single_meal_max_kcal?: number | null;
            /** Source Priority */
            source_priority?: string[];
        };
        /** SettingsOut */
        SettingsOut: {
            effective: components["schemas"]["PersonSettings"];
            /** Stored */
            stored: {
                [key: string]: unknown;
            };
        };
        /** SourceCoverageOut */
        SourceCoverageOut: {
            /** Source */
            source: string;
            /**
             * First Day
             * Format: date
             */
            first_day: string;
            /**
             * Last Day
             * Format: date
             */
            last_day: string;
            /** Days */
            days: number;
        };
        /** SupplementIn */
        SupplementIn: {
            /** Name */
            name: string;
            /** Dose Amount */
            dose_amount?: number | null;
            /** Dose Unit */
            dose_unit?: string | null;
            /**
             * Nutrients Per Day
             * @description Beitrag pro Tag, z. B. {"zinc_mg": 15}
             */
            nutrients_per_day?: {
                [key: string]: number;
            };
            /**
             * Taking
             * @default true
             */
            taking: boolean;
            /** Time Of Day */
            time_of_day?: string | null;
            /** Note */
            note?: string | null;
        };
        /** SupplementInPatch */
        SupplementInPatch: {
            /** Name */
            name?: string | null;
            /** Dose Amount */
            dose_amount?: number | null;
            /** Dose Unit */
            dose_unit?: string | null;
            /**
             * Nutrients Per Day
             * @description Beitrag pro Tag, z. B. {"zinc_mg": 15}
             */
            nutrients_per_day?: {
                [key: string]: number;
            } | null;
            /** Taking */
            taking?: boolean | null;
            /** Time Of Day */
            time_of_day?: string | null;
            /** Note */
            note?: string | null;
        };
        /** SupplementOut */
        SupplementOut: {
            /** Name */
            name: string;
            /** Dose Amount */
            dose_amount?: number | null;
            /** Dose Unit */
            dose_unit?: string | null;
            /**
             * Nutrients Per Day
             * @description Beitrag pro Tag, z. B. {"zinc_mg": 15}
             */
            nutrients_per_day?: {
                [key: string]: number;
            };
            /**
             * Taking
             * @default true
             */
            taking: boolean;
            /** Time Of Day */
            time_of_day?: string | null;
            /** Note */
            note?: string | null;
            /** Id */
            id: number;
        };
        /** TargetsOut */
        TargetsOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Day Type */
            day_type: string;
            target: components["schemas"]["MacroOut"];
            /** Slots */
            slots: {
                [key: string]: components["schemas"]["MacroOut"];
            };
            /** Shares */
            shares: {
                [key: string]: number;
            };
            tdee: components["schemas"]["TdeeOut"];
            body: components["schemas"]["BodyOut"];
            goal: components["schemas"]["app__api__targets__GoalOut"];
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
        };
        /** TdeeOut */
        TdeeOut: {
            /** Tdee Kcal */
            tdee_kcal: number;
            /** Device Kcal */
            device_kcal: number | null;
            /** Implied Kcal */
            implied_kcal: number | null;
            /** Confidence */
            confidence: number;
            /** Method */
            method: string;
            /** Notes */
            notes: string[];
        };
        /** TrainingItemIn */
        TrainingItemIn: {
            /**
             * Weekday
             * @description 0 = Montag … 6 = Sonntag
             */
            weekday: number;
            /** Session Type */
            session_type: string;
            /**
             * Intensity
             * @enum {string}
             */
            intensity: "easy" | "moderate" | "hard";
            /** Start Time */
            start_time?: string | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Expected Kcal */
            expected_kcal?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Note */
            note?: string | null;
        };
        /** TrainingItemInPatch */
        TrainingItemInPatch: {
            /**
             * Weekday
             * @description 0 = Montag … 6 = Sonntag
             */
            weekday?: number | null;
            /** Session Type */
            session_type?: string | null;
            /** Intensity */
            intensity?: ("easy" | "moderate" | "hard") | null;
            /** Start Time */
            start_time?: string | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Expected Kcal */
            expected_kcal?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Note */
            note?: string | null;
        };
        /** TrainingItemOut */
        TrainingItemOut: {
            /**
             * Weekday
             * @description 0 = Montag … 6 = Sonntag
             */
            weekday: number;
            /** Session Type */
            session_type: string;
            /**
             * Intensity
             * @enum {string}
             */
            intensity: "easy" | "moderate" | "hard";
            /** Start Time */
            start_time?: string | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Expected Kcal */
            expected_kcal?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Note */
            note?: string | null;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarningOut */
        WarningOut: {
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
        };
        /**
         * WeightOut
         * @description Gewicht aus der zusammengeführten Tagesreihe.
         */
        WeightOut: {
            /** Latest Kg */
            latest_kg: number | null;
            /** Latest Date */
            latest_date: string | null;
            /** Trend Kg Per Week */
            trend_kg_per_week: number | null;
            /** Trend N Points */
            trend_n_points: number;
            /** Points */
            points: components["schemas"]["WeightPoint"][];
        };
        /** WeightPoint */
        WeightPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Kg */
            kg: number;
        };
        /** WorkoutOut */
        WorkoutOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Duration Min */
            duration_min: number;
            /** Active Kcal */
            active_kcal: number | null;
            /** Avg Hr */
            avg_hr: number | null;
            /** Max Hr */
            max_hr: number | null;
            /** Distance Km */
            distance_km: number | null;
            /** Source */
            source: string;
        };
        /** WorkoutTypeStat */
        WorkoutTypeStat: {
            /** Count */
            count: number;
            /** Minutes */
            minutes: number;
        };
        /** WorkoutWeekOut */
        WorkoutWeekOut: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Iso Week */
            iso_week: string;
            /** Count */
            count: number;
            /** Total Minutes */
            total_minutes: number;
            /** By Type */
            by_type: {
                [key: string]: components["schemas"]["WorkoutTypeStat"];
            };
        };
        /** GoalOut */
        app__api__schemas__GoalOut: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lose" | "maintain" | "gain";
            /** Rate Kg Per Week */
            rate_kg_per_week: number | null;
            /** Kcal Modifier Pct */
            kcal_modifier_pct: number | null;
            /** Protein G Per Kg */
            protein_g_per_kg: number | null;
            /** Fat Pct */
            fat_pct: number | null;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GoalOut */
        app__api__targets__GoalOut: {
            /** Kind */
            kind: string;
            /** Rate Kg Per Week */
            rate_kg_per_week: number | null;
            /** Applied Rate Kg Per Week */
            applied_rate_kg_per_week: number | null;
            /** Valid From */
            valid_from: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
        };
    };
    patch_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings__api_me_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    put_settings_api_me_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_me_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__schemas__GoalOut"][];
                };
            };
        };
    };
    create_goal_api_me_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__schemas__GoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_goal_api_me_goals_active_get: {
        parameters: {
            query?: {
                on?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__api__schemas__GoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_me_supplements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementOut"][];
                };
            };
        };
    };
    create_item_api_me_supplements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_me_supplements__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_item_api_me_supplements__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_me_supplements__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_me_supplements__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplementInPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_me_nutrient_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutrientRuleOut"][];
                };
            };
        };
    };
    create_item_api_me_nutrient_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NutrientRuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutrientRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_me_nutrient_rules__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutrientRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_item_api_me_nutrient_rules__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NutrientRuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutrientRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_me_nutrient_rules__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_me_nutrient_rules__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NutrientRuleInPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutrientRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_me_training_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingItemOut"][];
                };
            };
        };
    };
    create_item_api_me_training_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_me_training_plan__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_item_api_me_training_plan__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_me_training_plan__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_me_training_plan__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingItemInPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_me_lab_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabRuleOut"][];
                };
            };
        };
    };
    create_item_api_me_lab_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabRuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_me_lab_rules__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_item_api_me_lab_rules__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabRuleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_me_lab_rules__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_me_lab_rules__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabRuleInPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_hae_api_me_imports_hae_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_hae_api_me_imports_hae_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_apple_health_api_me_imports_apple_health_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_apple_health_api_me_imports_apple_health_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_labs_api_me_imports_labs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_labs_api_me_imports_labs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imports_api_me_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"][];
                };
            };
        };
    };
    get_import_api_me_imports__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_api_me_health_daily_get: {
        parameters: {
            query?: {
                /** @description Erster Tag (einschließlich). */
                from?: string | null;
                /** @description Letzter Tag (einschließlich). */
                to?: string | null;
                /** @description Nur diese Quelle (Rohdaten). */
                source?: ("hae_zip" | "apple_health_xml") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workouts_api_me_workouts_get: {
        parameters: {
            query?: {
                /** @description Erster Tag (einschließlich). */
                from?: string | null;
                /** @description Letzter Tag (einschließlich). */
                to?: string | null;
                /** @description Nur diese Trainingsart (exakt). */
                type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_labs_api_me_labs_get: {
        parameters: {
            query?: {
                /** @description Nur auffällige Werte (L/H). */
                flagged?: boolean;
                /** @description Nur ausstehende Werte („folgt“). */
                pending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabReportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_labs_api_me_labs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestLabValueOut"][];
                };
            };
        };
    };
    get_lab_api_me_labs__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_me_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    get_targets_api_me_targets_get: {
        parameters: {
            query?: {
                /** @description Stichtag, Standard: heute */
                date?: string | null;
                /** @description Slot-Anteile überschreiben, z. B. `breakfast:1,dinner:0.5` */
                shares?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_manual_measurement_api_me_health_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualMeasurementIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualMeasurementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    spike_shopping_list_api_spike_shopping_list_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
