"""Start-Synonyme: typische deutsche Rezeptzutaten -> Suchbegriff im BLS-Katalog.

`SYNONYM_SEED` bildet den normalisierten Alias (siehe `ingredients.normalize_name`) auf den
vollständigen BLS-Namen (Spalte "Bezeichnung" der BLS 4.0) ab. Der Importer löst den Namen
beim BLS-Import in eine `ingredient.id` auf und legt daraus `ingredient_synonym`-Zeilen an.

Hinweise zu Annäherungen:
- Gewürze fehlen im BLS weitgehend; Oregano, Thymian, Majoran, Rosmarin und Salbei sind auf
  "Basilikum getrocknet" abgebildet (ähnliches Profil, Mengen sind klein).
- Kichererbsen, Kidneybohnen und Mais stehen für die Dose (abgetropft), Nudeln und Reis für
  Trockenware ("roh").
- Brühen sind **trinkfertig** (Gemüsebrühe, Hühnerbrühe, Fleischbrühe): Die Pulver-/Würfel-
  Einträge der BLS (51 g Salz je 100 g) sind nur über Aliase wie "Brühwürfel" oder
  "Gemüsebrühepulver" erreichbar. Eine reine Rinder-/Fleischbrühe heißt in der BLS "Fleischbrühe
  (Rind)", Fischfond "Fischbrühe", Gemüsefond "Gemüsebrühe".
- Frische Kräuter ohne BLS-Eintrag (Dill, Koriander, Minze, Kerbel, Estragon ...) sind auf
  "Petersilienblatt roh" abgebildet; Sammelbegriff "Kräuter" ebenso, getrocknete Mischungen
  auf "Basilikum getrocknet". Die Mengen sind klein (Bund 30-40 g).
- Gewürze, die die BLS nicht enthält (Paprikapulver, Zimt, Curry, Muskat, Kümmel, Kurkuma,
  Piment, Lorbeer, Kardamom, Nelken, Chiliflocken, Koriandersamen), sind bewusst **nicht**
  abgebildet: Die Zeile bleibt zur Prüfung offen bzw. wird manuell als Zutat angelegt.
- Schreibweisen, die `normalize_name` gleich macht ("Spinat TK" = "Spinat", "gemahlene Mandeln"
  = "Mandeln"), stehen nur einmal. Die Prüfung gegen die BLS-Namen läuft einmalig außerhalb des
  Repos (die BLS-Datei wird nicht eingecheckt).
"""

from app.calc.ingredients import normalize_name

# Schlüssel in natürlicher Schreibweise; sie werden unten normalisiert (Plural, Füllwörter).
_RAW_SEED: dict[str, str] = {
    # Eier
    "Ei": "Hühnerei roh",
    "Hühnerei": "Hühnerei roh",
    "Eigelb": "Hühnerei Eigelb, roh",
    "Eiweiß": "Hühnerei Eiklar, roh",
    "Eiklar": "Hühnerei Eiklar, roh",
    "Wachtelei": "Wachtelei roh",
    # Milch und Milchprodukte
    "Milch": "Vollmilch frisch, 3,5 % Fett, pasteurisiert",
    "Vollmilch": "Vollmilch frisch, 3,5 % Fett, pasteurisiert",
    "Milch 3,5 %": "Vollmilch frisch, 3,5 % Fett, pasteurisiert",
    "H-Milch": "H-Vollmilch 3,5 % Fett, ultrahocherhitzt",
    "Milch 1,5 %": "Milch fettarm, frisch, 1,5 % Fett, pasteurisiert",
    "fettarme Milch": "Milch fettarm, frisch, 1,5 % Fett, pasteurisiert",
    "Magermilch": "Milch entrahmt, frisch, höchstens 0,1 % Fett, pasteurisiert",
    "entrahmte Milch": "Milch entrahmt, frisch, höchstens 0,1 % Fett, pasteurisiert",
    "Buttermilch": "Buttermilch",
    "Sahne": "Schlagsahne mind. 30 % Fett",
    "Schlagsahne": "Schlagsahne mind. 30 % Fett",
    "Kaffeesahne": "Kaffeesahne mind. 10 % Fett",
    "Kochsahne": "Kaffeesahne mind. 10 % Fett",
    "Schmand": "Sauerrahm/Schmand, mind. 20 % Fett",
    "Sauerrahm": "Sauerrahm/Schmand, mind. 20 % Fett",
    "saure Sahne": "Sauerrahm/Saure Sahne, mind. 10 % Fett",
    "Crème fraîche": "Sauerrahm/Creme fraiche, 30 % Fett",
    "Creme fraiche": "Sauerrahm/Creme fraiche, 30 % Fett",
    "Joghurt": "Joghurt mild, mind. 3,5 % Fett",
    "Naturjoghurt": "Joghurt mild, mind. 3,5 % Fett",
    "Joghurt 3,5 %": "Joghurt mild, mind. 3,5 % Fett",
    "Joghurt 1,5 %": "Joghurt fettarm, mind. 1,5 % bis max. 1,8 % Fett",
    "fettarmer Joghurt": "Joghurt fettarm, mind. 1,5 % bis max. 1,8 % Fett",
    "Magerjoghurt": "Joghurt aus entrahmter Milch, max. 0,5 % Fett",
    "Joghurt 0,1 %": "Joghurt aus entrahmter Milch, max. 0,5 % Fett",
    "griechischer Joghurt": "Sahnejoghurt mind. 10 % Fett",
    "Sojajoghurt": "Soja-Joghurtalternative ungesüßt",
    "Kefir": "Kefir mind. 3,5 % Fett",
    "Dickmilch": "Dickmilch/Sauermilch, mind. 3,5 % Fett",
    "Skyr": "Skyr, Frischkäse < 10 % Fett i. Tr.",
    "Quark": "Speisequark Halbfettstufe, 20 % Fett i. Tr.",
    "Speisequark": "Speisequark Halbfettstufe, 20 % Fett i. Tr.",
    "Magerquark": "Speisequark Magerstufe, Magerquark < 10 % Fett i. Tr.",
    "Quark 40 %": "Speisequark Fettstufe, 40 % Fett i. Tr.",
    "Sahnequark": "Speisequark Rahmstufe, 50 % Fett i. Tr.",
    "Hüttenkäse": "Körniger Frischkäse mind. 20 % Fett i. Tr.",
    "körniger Frischkäse": "Körniger Frischkäse mind. 20 % Fett i. Tr.",
    "Frischkäse": "Frischkäsezubereitung Natur, mind. 50 % Fett i. Tr.",
    "Doppelrahmfrischkäse": "Frischkäsezubereitung Natur, mind. 60 % Fett i. Tr.",
    "Frischkäse light": "Frischkäsezubereitung Natur < 10 % Fett i. Tr.",
    "Ziegenfrischkäse": "Frischkäse aus Ziegenmilch, Natur, mind. 45 % Fett i. Tr.",
    "Mozzarella": "Mozzarella mind. 45 % Fett i. Tr.",
    "Parmesan": "Parmesan mind. 30 % Fett i. Tr.",
    "Grana Padano": "Parmesan mind. 30 % Fett i. Tr.",
    "Gouda": "Gouda mind. 40 % Fett i. Tr.",
    "Käse": "Gouda mind. 40 % Fett i. Tr.",
    "Reibekäse": "Gouda mind. 40 % Fett i. Tr.",
    "Emmentaler": "Emmentaler mind. 45 % Fett i. Tr.",
    "Cheddar": "Chester (Cheddar) mind. 50 % Fett i. Tr.",
    "Edamer": "Edamer mind. 40 % Fett i. Tr.",
    "Bergkäse": "Bergkäse mind. 45 % Fett i. Tr.",
    "Tilsiter": "Tilsiter mind. 45 % Fett i. Tr.",
    "Appenzeller": "Appenzeller mind. 50 % Fett i. Tr.",
    "Raclettekäse": "Raclettekäse mind. 45 % Fett i. Tr.",
    "Feta": "Feta mind. 45 % Fett i. Tr.",
    "Schafskäse": "Feta mind. 45 % Fett i. Tr.",
    "Hirtenkäse": "Salzlakenkäse aus Kuhmilch, Hirtenkäse, mind. 45 % Fett i. Tr.",
    "Camembert": "Camembert mind. 45 % Fett i. Tr.",
    "Gorgonzola": "Gorgonzola mind. 48 % Fett i. Tr.",
    "Roquefort": "Roquefort mind. 50 % Fett i. Tr.",
    "Halloumi": "Halloumi Grillkäse",
    "Ricotta": "Ricotta, Molkeneiweißkäse, mind. 45 % Fett i. Tr.",
    "Mascarpone": "Mascarpone mind. 80 % Fett i. Tr.",
    "Ziegenkäse": "Weichkäse aus Ziegenmilch, mind. 45 % Fett i. Tr.",
    "Schmelzkäse": "Schmelzkäse schnittfest, mind. 45 % Fett i. Tr.",
    "Kochkäse": "Kochkäse mind. 10 % Fett i. Tr.",
    # Fette und Öle
    "Butter": "Butter mild gesäuert",
    "Butterschmalz": "Butterschmalz",
    "Margarine": "Pflanzenmargarine Vollfett, angereichert mit Vitaminen",
    "Schmalz": "Schweinefett/Schweineschmalz",
    "Olivenöl": "Olivenöl",
    "Rapsöl": "Rapsöl/Rüböl",
    "Pflanzenöl": "Rapsöl/Rüböl",
    "Speiseöl": "Rapsöl/Rüböl",
    "Öl": "Rapsöl/Rüböl",
    "Sonnenblumenöl": "Sonnenblumenöl",
    "Sesamöl": "Sesamöl",
    "Kokosöl": "Kokosöl",
    "Leinöl": "Leinöl",
    "Walnussöl": "Walnussöl",
    "Erdnussöl": "Erdnussöl",
    "Kürbiskernöl": "Kürbiskernöl",
    # Fleisch, Wurst
    "Hackfleisch": "Rind/Schwein, Hackfleisch gemischt, roh",
    "Hackfleisch gemischt": "Rind/Schwein, Hackfleisch gemischt, roh",
    "Hack": "Rind/Schwein, Hackfleisch gemischt, roh",
    "Rinderhack": "Rind Hackfleisch, roh",
    "Rinderhackfleisch": "Rind Hackfleisch, roh",
    "Schweinehack": "Schwein Hackfleisch, roh",
    "Schweinehackfleisch": "Schwein Hackfleisch, roh",
    "Kalbshackfleisch": "Kalb Hackfleisch, roh",
    "Tatar": "Rind Tatar/Schabefleisch, roh",
    "Hähnchenbrust": "Hähnchen Brustfilet, roh",
    "Hähnchenbrustfilet": "Hähnchen Brustfilet, roh",
    "Hähnchenfilet": "Hähnchen Brustfilet, roh",
    "Hühnerbrust": "Hähnchen Brustfilet, roh",
    "Hühnerbrustfilet": "Hähnchen Brustfilet, roh",
    "Hähnchenkeule": "Hähnchen Oberschenkel, mit Haut, roh",
    "Hähnchenschenkel": "Hähnchen Oberschenkel, mit Haut, roh",
    "Hähnchenflügel": "Hähnchen Flügel, mit Haut, roh",
    "Hähnchen": "Hähnchen ganz, entbeint, mit Haut, roh",
    "Hähnchenleber": "Hähnchen Leber, roh",
    "Putenbrust": "Pute Brust, ohne Haut, roh",
    "Putenschnitzel": "Pute Brust, ohne Haut, roh",
    "Putenfleisch": "Pute Fleisch, mit Haut, roh",
    "Schweinefilet": "Schwein Filet/Lende, roh",
    "Schweineschnitzel": "Schwein Schnitzel (Oberschale) roh",
    "Schweinenacken": "Schwein Kammbraten, roh",
    "Schweinebauch": "Schwein Bauch (wie gewachsen) roh",
    "Schweinegulasch": "Schwein Gulasch (Restbug) roh",
    "Rinderfilet": "Rind Filet/Lende, roh",
    "Rindersteak": "Rind Steak (Rücken) roh",
    "Rindergulasch": "Rind Gulasch (Bug) roh",
    "Roastbeef": "Rind Roastbeef (Rücken) roh",
    "Rinderleber": "Rind Leber, roh",
    "Kalbsschnitzel": "Kalb Schnitzel (Keule) roh",
    "Bacon": "Schwein Frühstücksspeck, Rohpökelware, geräuchert",
    "Frühstücksspeck": "Schwein Frühstücksspeck, Rohpökelware, geräuchert",
    "Speck": "Schwein Bauchspeck, Rohpökelware, geräuchert",
    "Schinken": "Schwein Kochschinken, Kochpökelware",
    "Kochschinken": "Schwein Kochschinken, Kochpökelware",
    "Schinkenwürfel": "Schwein Kochschinken, Kochpökelware",
    "Rohschinken": "Parmaschinken",
    "Parmaschinken": "Parmaschinken",
    "Salami": "Salami",
    "Leberwurst": "Leberwurst einfach",
    "Fleischwurst": "Fleischwurst",
    "Lyoner": "Lyoner/Lyoner Wurst",
    "Wiener Würstchen": "Wiener Würstchen",
    "Bockwurst": "Bockwurst",
    "Bratwurst": "Rostbratwurst",
    "Mettwurst": "Mettwurst",
    "Putenbrustaufschnitt": "Putenbrust, Kochpökelware, geräuchert",
    "Tofu": "Tofu",
    "Seidentofu": "Seidentofu",
    "Seitan": "Fleischersatz glutenhaltig (Seitan)",
    # Fisch und Meeresfrüchte
    "Lachs": "Lachs roh",
    "Lachsfilet": "Lachs roh",
    "Räucherlachs": "Lachs geräuchert (Räucherlachs)",
    "Thunfisch": "Thunfisch roh",
    "Thunfisch Dose": "Thunfisch in Öl, Konserve, abgetropft",
    "Forelle": "Forelle roh",
    "Kabeljau": "Dorsch/Kabeljau, roh",
    "Dorsch": "Dorsch/Kabeljau, roh",
    "Seelachs": "Köhler/Seelachs, roh",
    "Hering": "Hering roh",
    "Matjes": "Matjeshering mild gesalzen",
    "Makrele": "Makrele roh",
    "Garnele": "Garnele/Granat/Krabbe, roh",
    "Sardine": "Sardine roh",
    "Zander": "Zander roh",
    "Scholle": "Goldbutt/Scholle, roh",
    "Rotbarsch": "Rotbarsch/Goldbarsch, roh",
    "Pangasius": "Pangasius/Schlankwels, roh",
    "Miesmuschel": "Miesmuschel roh",
    "Tintenfisch": "Tintenfisch roh",
    # Gemüse
    "Zwiebel": "Speisezwiebel roh",
    "rote Zwiebel": "Speisezwiebel roh",
    "Gemüsezwiebel": "Speisezwiebel roh",
    "Schalotte": "Schalotte roh",
    "Frühlingszwiebel": "Frühlingszwiebel/Lauchzwiebel, roh",
    "Lauchzwiebel": "Frühlingszwiebel/Lauchzwiebel, roh",
    "Knoblauch": "Knoblauch roh",
    "Kartoffel": "Kartoffel geschält, roh",
    "Süßkartoffel": "Batate/Süßkartoffel, roh",
    "Karotte": "Karotte/Möhre, roh",
    "Möhre": "Karotte/Möhre, roh",
    "Mohrrübe": "Karotte/Möhre, roh",
    "Sellerie": "Knollensellerie roh",
    "Knollensellerie": "Knollensellerie roh",
    "Staudensellerie": "Bleichsellerie roh",
    "Stangensellerie": "Bleichsellerie roh",
    "Lauch": "Porree/Lauch, roh",
    "Porree": "Porree/Lauch, roh",
    "Suppengrün": "Suppengrün/Suppenkraut, roh",
    "Tomate": "Tomate roh",
    "Cherrytomate": "Tomate roh",
    "Cocktailtomate": "Tomate roh",
    "Strauchtomate": "Tomate roh",
    "Dosentomate": "Tomate Konserve",
    "stückige Tomaten": "Tomate Konserve",
    "passierte Tomaten": "Tomaten passiert/Tomatenpüree",
    "Tomatenmark": "Tomatenmark",
    "Paprika": "Gemüsepaprika rot, roh",
    "rote Paprika": "Gemüsepaprika rot, roh",
    "gelbe Paprika": "Gemüsepaprika gelb, roh",
    "grüne Paprika": "Gemüsepaprika grün, roh",
    "Spitzpaprika": "Gemüsepaprika rot, roh",
    "Chili": "Pfefferschote rot, roh",
    "Chilischote": "Pfefferschote rot, roh",
    "Peperoni": "Pfefferschote grün, roh",
    "Zucchini": "Zucchini roh",
    "Aubergine": "Aubergine roh",
    "Gurke": "Gurke roh",
    "Salatgurke": "Gurke roh",
    "Brokkoli": "Broccoli roh",
    "Blumenkohl": "Blumenkohl roh",
    "Rosenkohl": "Rosenkohl roh",
    "Rotkohl": "Rotkohl roh",
    "Weißkohl": "Weißkohl roh",
    "Spitzkohl": "Spitzkohl roh",
    "Wirsing": "Wirsing roh",
    "Grünkohl": "Grünkohl roh",
    "Chinakohl": "Chinakohl roh",
    "Pak Choi": "Pak Choi roh",
    "Kohlrabi": "Kohlrabi roh",
    "Spinat": "Spinat roh",
    "Blattspinat": "Spinat roh",
    "Mangold": "Mangold roh",
    "Rucola": "Rucola roh",
    "Feldsalat": "Feldsalat/Rapunzel, roh",
    "Kopfsalat": "Kopfsalat roh",
    "Salat": "Kopfsalat roh",
    "Eisbergsalat": "Eisbergsalat roh",
    "Romanasalat": "Römischer Salat/Romanasalat, roh",
    "Radieschen": "Radieschen roh",
    "Rettich": "Rettich roh",
    "Rote Bete": "Rote Rübe/Rote Bete, roh",
    "Pastinake": "Pastinake roh",
    "Fenchel": "Gemüsefenchel roh",
    "Spargel": "Spargel roh",
    "Kürbis": "Kürbis Hokkaido (C. maxima) roh",
    "Hokkaido": "Kürbis Hokkaido (C. maxima) roh",
    "Mais": "Zuckermais roh",
    "Dosenmais": "Zuckermais Konserve, abgetropft",
    "Erbse": "Erbse grün, roh",
    "grüne Bohne": "Bohne grün, roh",
    "Champignon": "Champignon roh",
    "Pilze": "Mischpilze roh",
    "Pfifferling": "Pfifferling roh",
    "Austernpilz": "Austernpilz roh",
    "Steinpilz": "Steinpilz roh",
    "Shiitake": "Shiitakepilz roh",
    "Avocado": "Avocado roh",
    "Olive": "Oliven grün, gesäuert, abgetropft",
    "schwarze Oliven": "Oliven geschwärzt, in Salzlake, abgetropft",
    "Kapern": "Kapern gesäuert, abgetropft",
    "saure Gurke": "Gurke gesäuert (Gewürzgurke) abgetropft",
    "Gewürzgurke": "Gurke gesäuert (Gewürzgurke) abgetropft",
    "Essiggurke": "Gurke gesäuert (Gewürzgurke) abgetropft",
    "Salzgurke": "Salzgurke/Salzdillgurke, milchsauer fermentiert, abgetropft",
    "Sauerkraut": "Sauerkraut abgetropft, roh",
    "Ingwer": "Ingwer/Ingwerwurzel, roh",
    "Meerrettich": "Meerrettich roh",
    # Hülsenfrüchte
    "Kichererbse": "Kichererbse reif, Konserve, abgetropft",
    "Kidneybohne": "Kidneybohne reif, Konserve, abgetropft",
    "Linse": "Linse reif",
    "rote Linse": "Linse rot reif",
    "weiße Bohne": "Gartenbohne reif",
    "Sojabohne": "Sojabohne reif",
    "Edamame": "Sojabohne unreif (Edamame) roh",
    "Erdnuss": "Erdnuss geröstet",
    "Hummus": "Hummus/Kichererbsenmus",
    "Tahin": "Tahin (Sesammus)",
    # Obst
    "Apfel": "Apfel roh",
    "Birne": "Birne roh",
    "Banane": "Banane roh",
    "Orange": "Orange roh",
    "Mandarine": "Mandarine roh",
    "Clementine": "Clementine roh",
    "Zitrone": "Zitrone roh",
    "Limette": "Limette roh",
    "Grapefruit": "Grapefruit roh",
    "Erdbeere": "Erdbeere roh",
    "Himbeere": "Himbeere roh",
    "Heidelbeere": "Heidelbeere roh",
    "Blaubeere": "Heidelbeere roh",
    "Brombeere": "Brombeere roh",
    "Johannisbeere": "Johannisbeere rot, roh",
    "Kirsche": "Süßkirsche roh",
    "Pflaume": "Pflaume roh",
    "Zwetschge": "Zwetschge roh",
    "Pfirsich": "Pfirsich roh",
    "Nektarine": "Nektarine roh",
    "Aprikose": "Aprikose roh",
    "Weintraube": "Weintraube roh",
    "Mango": "Mango roh",
    "Ananas": "Ananas roh",
    "Kiwi": "Kiwi roh",
    "Honigmelone": "Honigmelone roh",
    "Wassermelone": "Wassermelone roh",
    "Feige": "Feige roh",
    "Rhabarber": "Rhabarber roh",
    "Granatapfel": "Granatapfel roh",
    "Papaya": "Papaya roh",
    "Dattel": "Dattel getrocknet",
    "Rosine": "Rosine/Sultanine (Weinbeere getrocknet)",
    "Trockenaprikose": "Aprikose getrocknet",
    "Cranberry": "Cranberries getrocknet, gezuckert",
    "Zitronensaft": "Zitronensaft",
    "Orangensaft": "Orangensaft",
    "Apfelsaft": "Apfelsaft",
    "Apfelmus": "Apfelkompott/Apfelmus, gezuckert, Konserve",
    "Kokosmilch": "Kokosmilch/Kokosnussmilch",
    # Nüsse und Samen
    "Mandel": "Mandel süß",
    "Walnuss": "Walnuss",
    "Haselnuss": "Haselnuss",
    "Cashewkern": "Cashewkern",
    "Cashew": "Cashewkern",
    "Pistazie": "Pistazie",
    "Pinienkern": "Pinienkern",
    "Sonnenblumenkern": "Sonnenblumenkern",
    "Kürbiskern": "Kürbiskern",
    "Sesam": "Sesam",
    "Leinsamen": "Leinsamen",
    "Chiasamen": "Chia-Samen",
    "Mohn": "Mohn",
    "Erdnussmus": "Erdnussmus",
    "Erdnussbutter": "Erdnussmus",
    "Mandelmus": "Mandelmus",
    "Nuss-Nougat-Creme": "Nuss-Nougat-Creme",
    # Getreide, Nudeln, Reis, Brot
    "Haferflocken": "Hafer Flocken",
    "Haferkleie": "Hafer Kleie",
    "Mehl": "Weizen Mehl, Type 405",
    "Weizenmehl": "Weizen Mehl, Type 405",
    "Weizenmehl Type 550": "Weizen Mehl, Type 550",
    "Dinkelmehl": "Dinkel Mehl, Type 630",
    "Vollkornmehl": "Weizen Vollkornmehl",
    "Roggenmehl": "Roggen Mehl, Type 815",
    "Reis": "Reis poliert, roh",
    "Basmatireis": "Reis poliert, roh",
    "Jasminreis": "Reis poliert, roh",
    "Naturreis": "Reis unpoliert, roh",
    "Vollkornreis": "Reis unpoliert, roh",
    "Nudel": "Teigwaren eifrei, roh",
    "Pasta": "Teigwaren eifrei, roh",
    "Spaghetti": "Teigwaren eifrei, roh",
    "Penne": "Teigwaren eifrei, roh",
    "Fusilli": "Teigwaren eifrei, roh",
    "Makkaroni": "Teigwaren eifrei, roh",
    "Vollkornnudeln": "Vollkornteigwaren eifrei, roh",
    "Eiernudeln": "Eierteigwaren roh",
    "Couscous": "Couscous (Hartweizen) roh",
    "Bulgur": "Bulgur (Hartweizen) roh",
    "Quinoa": "Quinoa weiß, roh",
    "Hirse": "Hirse roh",
    "Polenta": "Mais Grieß",
    "Grieß": "Weichweizen Grieß",
    "Gnocchi": "Gnocchi roh",
    "Speisestärke": "Mais Stärke",
    "Maisstärke": "Mais Stärke",
    "Kartoffelstärke": "Kartoffelstärke (Kartoffelmehl)",
    "Paniermehl": "Paniermehl/Semmelbrösel/Semmelmehl",
    "Semmelbrösel": "Paniermehl/Semmelbrösel/Semmelmehl",
    "Cornflakes": "Cornflakes gesüßt",
    "Müsli": "Müsli Basismischung (ohne Trockenfrüchte) ungesüßt",
    "Reiswaffel": "Reiswaffeln ungesalzen",
    "Tortilla": "Weizentortilla",
    "Wrap": "Weizentortilla",
    "Pizzateig": "Pizzateig (mit Hefe) roh",
    "Blätterteig": "Blätterteig eifrei, roh",
    "Brot": "Roggenmischbrot",
    "Vollkornbrot": "Vollkornbrot",
    "Roggenbrot": "Roggenbrot",
    "Weißbrot": "Weizenbrot/Weißbrot",
    "Brötchen": "Weizenbrötchen",
    "Vollkornbrötchen": "Weizenvollkornbrötchen",
    "Knäckebrot": "Roggenknäckebrot",
    "Fladenbrot": "Weizenfladenbrot",
    # Backzutaten, Süßes
    "Zucker": "Zucker weiß (Raffinadezucker/Weißzucker)",
    "Puderzucker": "Puderzucker",
    "brauner Zucker": "Zucker braun (Kandisfarin/Rohzucker)",
    "Vanillezucker": "Vanillezucker",
    "Honig": "Honig",
    "Ahornsirup": "Ahornsirup",
    "Marmelade": "Konfitüre extra",
    "Konfitüre": "Konfitüre extra",
    "Zartbitterschokolade": "Zartbitter-/Halbbitterschokolade",
    "Schokolade": "Schokolade",
    "Milchschokolade": "Milchschokolade",
    "Kakao": "Kakaopulver stark entölt",
    "Kakaopulver": "Kakaopulver stark entölt",
    "Backpulver": "Backpulver",
    "Hefe": "Backhefe frisch (Frischbackhefe)",
    "Trockenhefe": "Backhefe getrocknet (Trockenbackhefe)",
    "Gelatine": "Gelatine/Speisegelatine",
    # Salz, Gewürze, Kräuter, Würzmittel
    "Salz": "Speisesalz/Siedesalz/Tafelsalz",
    "Jodsalz": "Speisesalz jodiert/Jodsalz",
    "Meersalz": "Meersalz",
    "Pfeffer": "Pfeffer schwarz, getrocknet",
    "Basilikum": "Basilikum roh",
    "Petersilie": "Petersilienblatt roh",
    "Schnittlauch": "Schnittlauch roh",
    "Kresse": "Gartenkresse roh",
    "Bärlauch": "Bärlauch roh",
    "Oregano": "Basilikum getrocknet",
    "Thymian": "Basilikum getrocknet",
    "Majoran": "Basilikum getrocknet",
    "Rosmarin": "Basilikum getrocknet",
    "Salbei": "Basilikum getrocknet",
    "Paprikapulver": "Basilikum getrocknet",
    "Paprika edelsüß": "Basilikum getrocknet",
    "Chiliflocken": "Basilikum getrocknet",
    "Chilipulver": "Basilikum getrocknet",
    "Cayennepfeffer": "Basilikum getrocknet",
    "Curry": "Basilikum getrocknet",
    "Currypulver": "Basilikum getrocknet",
    "Zimt": "Basilikum getrocknet",
    "Muskat": "Basilikum getrocknet",
    "Muskatnuss": "Basilikum getrocknet",
    "Kümmel": "Basilikum getrocknet",
    "Kurkuma": "Basilikum getrocknet",
    "Piment": "Basilikum getrocknet",
    "Lorbeer": "Basilikum getrocknet",
    "Lorbeerblatt": "Basilikum getrocknet",
    "Kardamom": "Basilikum getrocknet",
    "Nelken": "Basilikum getrocknet",
    "Koriandersamen": "Basilikum getrocknet",
    "Gewürzmischung": "Basilikum getrocknet",
    "Senf": "Senf mittelscharf",
    "Ketchup": "Tomatenketchup",
    "Mayonnaise": "Mayonnaise (Fertigprodukt)",
    "Essig": "Weinessig",
    "Balsamico": "Balsamicoessig",
    "Apfelessig": "Apfelessig",
    "Sojasauce": "Sojasauce/Sojasoße",
    "Gemüsebrühe": "Gemüsebrühe",
    "Brühe": "Gemüsebrühe",
    "Hühnerbrühe": "Hühnerbrühe",
    "Sambal Oelek": "Sambal Oelek, Würzpaste",
    # Getränke
    "Wasser": "Trinkwasser",
    "Mineralwasser": "Natürliches Mineralwasser",
    "Kaffee": "Kaffee (Getränk)",
    "Mandeldrink": "Mandeldrink ungesüßt",
    "Sojadrink": "Sojadrink ungesüßt",
    "Haferdrink": "Haferdrink ungesüßt",
    "Reisdrink": "Reisdrink ungesüßt",
    # --- Ergänzungen aus Tests mit echten Rezepten ---
    # Samen, Nüsse
    "Sesamkörner": "Sesam",
    "Sesamsamen": "Sesam",
    "Sesamsaat": "Sesam",
    "gerösteter Sesam": "Sesam geröstet ohne Fett",
    "Leinsamen geschrotet": "Leinsamen geschrotet",
    "geschrotete Leinsamen": "Leinsamen geschrotet",
    "Leinsaat": "Leinsamen",
    "Chia": "Chia-Samen",
    "Chiasaat": "Chia-Samen",
    "Sonnenblumenkerne": "Sonnenblumenkern",
    "Kürbiskerne": "Kürbiskern",
    "Mohnsamen": "Mohn",
    "Mandelblättchen": "Mandel süß",
    "Mandelstifte": "Mandel süß",
    "gehobelte Mandeln": "Mandel süß",
    "Mandeln blanchiert": "Mandel süß, blanchiert",
    "Erdnusskerne": "Erdnuss geröstet",
    "Paranuss": "Paranuss",
    "Pekannuss": "Pekannuss",
    "Macadamia": "Macadamianuss",
    "Macadamianuss": "Macadamianuss",
    "Walnusskerne": "Walnuss",
    "Haselnusskerne": "Haselnuss",
    "Kokosraspel": "Kokos Fruchtfleisch, geraspelt, getrocknet",
    "Kokosflocken": "Kokos Fruchtfleisch, geraspelt, getrocknet",
    "Kokosnuss": "Kokos Fruchtfleisch, roh",
    "Cashewmus": "Cashewnussmus",
    "Haselnussmus": "Haselnussmus",
    "Studentenfutter": "Studentenfutter",
    # Gemüse
    "Kirschtomate": "Tomate roh",
    "Datteltomate": "Tomate roh",
    "Rispentomate": "Tomate roh",
    "Romatomate": "Tomate roh",
    "Fleischtomate": "Tomate roh",
    "Eiertomate": "Tomate roh",
    "Snacktomate": "Tomate roh",
    "getrocknete Tomaten": "Tomate getrocknet",
    "Tomaten getrocknet": "Tomate getrocknet",
    "Tomatenpüree": "Tomaten passiert/Tomatenpüree",
    "Passata": "Tomaten passiert/Tomatenpüree",
    "Snackgurke": "Gurke roh",
    "Minigurke": "Gurke roh",
    "Schlangengurke": "Gurke roh",
    "Paprikaschote": "Gemüsepaprika rot, roh",
    "Gemüsepaprika": "Gemüsepaprika rot, roh",
    "Snackpaprika": "Gemüsepaprika rot, roh",
    "Minipaprika": "Gemüsepaprika rot, roh",
    "Spitzpaprikaschote": "Gemüsepaprika rot, roh",
    "orange Paprika": "Gemüsepaprika gelb, roh",
    "rote Paprikaschote": "Gemüsepaprika rot, roh",
    "gelbe Paprikaschote": "Gemüsepaprika gelb, roh",
    "grüne Paprikaschote": "Gemüsepaprika grün, roh",
    "rote Spitzpaprika": "Gemüsepaprika rot, roh",
    "gelbe Spitzpaprika": "Gemüsepaprika gelb, roh",
    "grüne Spitzpaprika": "Gemüsepaprika grün, roh",
    "Pfefferschote": "Pfefferschote rot, roh",
    "Peperoncino": "Pfefferschote rot, roh",
    "Jalapeño": "Pfefferschote grün, roh",
    "Jalapeno": "Pfefferschote grün, roh",
    "Petersilienwurzel": "Wurzelpetersilie roh",
    "Wurzelpetersilie": "Wurzelpetersilie roh",
    "Petersilienblatt": "Petersilienblatt roh",
    "getrocknete Petersilie": "Petersilienblatt getrocknet",
    "Schnittlauchröllchen": "Schnittlauch roh",
    "getrockneter Schnittlauch": "Schnittlauch getrocknet",
    "getrocknetes Basilikum": "Basilikum getrocknet",
    "Knoblauchzehe": "Knoblauch roh",
    "Knoblauchpulver": "Knoblauch Pulver",
    "Zwiebelpulver": "Speisezwiebel Pulver",
    "Bundzwiebel": "Frühlingszwiebel/Lauchzwiebel, roh",
    "Zwiebeln rot": "Speisezwiebel roh",
    "Silberzwiebel": "Silberzwiebel roh",
    "Perlzwiebel": "Perlzwiebel roh",
    "Selleriestange": "Bleichsellerie roh",
    "Sellerieknolle": "Knollensellerie roh",
    "Bleichsellerie": "Bleichsellerie roh",
    "Pellkartoffel": "Kartoffel ungeschält, roh",
    "Salzkartoffel": "Kartoffel geschält, roh",
    "Butternut": "Kürbis Pumpkin (C. pepo) roh",
    "Butternutkürbis": "Kürbis Pumpkin (C. pepo) roh",
    "Hokkaidokürbis": "Kürbis Hokkaido (C. maxima) roh",
    "Muskatkürbis": "Kürbis Pumpkin (C. pepo) roh",
    "Kürbis Butternut": "Kürbis Pumpkin (C. pepo) roh",
    "Babyspinat": "Spinat roh",
    "Rahmspinat": "Spinat tiefgefroren",
    "Mini-Romana": "Römischer Salat/Romanasalat, roh",
    "Romana": "Römischer Salat/Romanasalat, roh",
    "Lollo Rosso": "Schnittsalat/Pflücksalat, roh",
    "Pflücksalat": "Schnittsalat/Pflücksalat, roh",
    "Eichblattsalat": "Schnittsalat/Pflücksalat, roh",
    "Endivie": "Endivie/Escariol, roh",
    "Chicorée": "Chicoree roh",
    "Radicchio": "Radicchio roh",
    "Zuckerschote": "Zuckererbse roh",
    "Prinzessbohnen": "Bohne grün, roh",
    "Brechbohnen": "Bohne grün, roh",
    "Buschbohnen": "Bohne grün, roh",
    "Stangenbohnen": "Bohne grün, roh",
    "dicke Bohnen": "Dicke Bohne unreif, roh",
    "Saubohnen": "Dicke Bohne unreif, roh",
    "Maiskolben": "Zuckermais roh",
    "Zuckermais": "Zuckermais roh",
    "Broccoli": "Broccoli roh",
    "Brokkoliröschen": "Broccoli roh",
    "Blumenkohlröschen": "Blumenkohl roh",
    "Romanesco": "Romanesco roh",
    "Kohl": "Weißkohl roh",
    "Weisskohl": "Weißkohl roh",
    "Wirsingkohl": "Wirsing roh",
    "Rotkraut": "Rotkohl roh",
    "Blaukraut": "Rotkohl roh",
    "Weißkraut": "Weißkohl roh",
    "Palmkohl": "Grünkohl roh",
    "Schwarzkohl": "Grünkohl roh",
    "Mairübe": "Weiße Rübe/Wasserrübe/Herbstrübe, roh",
    "Steckrübe": "Kohlrübe/Steckrübe, roh",
    "Kohlrübe": "Kohlrübe/Steckrübe, roh",
    "Topinambur": "Topinambur/Erdartischocke, roh",
    "Artischocke": "Artischocke roh",
    "Okra": "Okra roh",
    "Schwarzwurzel": "Schwarzwurzel roh",
    "Bambussprossen": "Bambussprossen roh",
    "Mungbohnensprossen": "Mungbohnensprossen/Mungbohnenkeimlinge, roh",
    "Sojasprossen": "Sojabohnensprossen/Sojabohnenkeimlinge, roh",
    "Sprossen": "Alfalfasprossen/Alfalfakeimlinge, roh",
    "Alfalfasprossen": "Alfalfasprossen/Alfalfakeimlinge, roh",
    "Champignons braun": "Champignon roh",
    "Egerling": "Champignon roh",
    "Kräuterseitling": "Austernpilz roh",
    "Seitling": "Austernpilz roh",
    "Pilzmischung": "Mischpilze roh",
    "getrocknete Steinpilze": "Steinpilz getrocknet",
    "Steinpilze getrocknet": "Steinpilz getrocknet",
    "Ajvar": "Ajvar Konserve",
    "Tomatensaft": "Gemüsesaft aus Tomate, mit Salz",
    "Karottensaft": "Gemüsesaft aus Karotte/Möhre",
    "Wasabi": "Wasabi roh",
    "Wasabipaste": "Wasabi-Paste Konserve",
    # Obst
    "Zitronenabrieb": "Zitrone roh",
    "Zitronenschale": "Zitrone roh",
    "Orangenschale": "Orange roh",
    "Limettensaft": "Limettensaft",
    "Granatapfelkerne": "Granatapfel roh",
    "Passionsfrucht": "Maracuja/Passionsfrucht, roh",
    "Maracuja": "Maracuja/Passionsfrucht, roh",
    "Kaki": "Kaki roh",
    "Quitte": "Quitte roh",
    "Stachelbeere": "Stachelbeere roh",
    "Preiselbeere": "Preiselbeere roh",
    "Sauerkirsche": "Sauerkirsche roh",
    "Mirabelle": "Mirabelle roh",
    "Cranberries": "Cranberries getrocknet, gezuckert",
    "Sultanine": "Rosine/Sultanine (Weinbeere getrocknet)",
    "Korinthen": "Korinthe (Weinbeere getrocknet)",
    "Backpflaume": "Pflaume getrocknet",
    "Trockenpflaume": "Pflaume getrocknet",
    "getrocknete Feigen": "Feige getrocknet",
    "getrocknete Mango": "Mango getrocknet",
    "getrocknete Aprikosen": "Aprikose getrocknet",
    "Apfelmark": "Apfelkompott/Apfelmark, ungesüßt, Konserve",
    # Milchprodukte, Käse
    "Naturjoghurt 3,5 %": "Joghurt mild, mind. 3,5 % Fett",
    "Joghurt natur": "Joghurt mild, mind. 3,5 % Fett",
    "Joghurt mild": "Joghurt mild, mind. 3,5 % Fett",
    "Sahnejoghurt": "Sahnejoghurt mind. 10 % Fett",
    "Schafjoghurt": "Schafjoghurt",
    "Ayran": "Ayran, Joghurtgetränk, gesalzen",
    "Schlagsahne 30 %": "Schlagsahne mind. 30 % Fett",
    "Sahne 30 %": "Schlagsahne mind. 30 % Fett",
    "Schlagobers": "Schlagsahne mind. 30 % Fett",
    "Rahm": "Schlagsahne mind. 30 % Fett",
    "Crème légère": "Sauerrahm/Saure Sahne, mind. 10 % Fett",
    "Schmand 20 %": "Sauerrahm/Schmand, mind. 20 % Fett",
    "Sauerrahm 10 %": "Sauerrahm/Saure Sahne, mind. 10 % Fett",
    "Frischkäse natur": "Frischkäsezubereitung Natur, mind. 50 % Fett i. Tr.",
    "Frischkäsezubereitung": "Frischkäsezubereitung Natur, mind. 50 % Fett i. Tr.",
    "Philadelphia": "Frischkäsezubereitung Natur, mind. 50 % Fett i. Tr.",
    "Kräuterfrischkäse": "Frischkäsezubereitung mind. 60 % Fett i. Tr., mit Gemüse/Kräutern",
    "Frischkäse Kräuter": "Frischkäsezubereitung mind. 60 % Fett i. Tr., mit Gemüse/Kräutern",
    "Frischkäse leicht": "Frischkäsezubereitung Natur < 10 % Fett i. Tr.",
    "fettarmer Frischkäse": "Frischkäsezubereitung Natur < 10 % Fett i. Tr.",
    "Hüttenkäse light": "Körniger Frischkäse < 10 % Fett i. Tr.",
    "Parmigiano": "Parmesan mind. 30 % Fett i. Tr.",
    "Parmigiano Reggiano": "Parmesan mind. 30 % Fett i. Tr.",
    "Mozzarella light": "Mozzarella mind. 20 % Fett i. Tr.",
    "Büffelmozzarella": "Mozzarella mind. 45 % Fett i. Tr.",
    "Fetakäse": "Feta mind. 45 % Fett i. Tr.",
    "Salzlakenkäse": "Salzlakenkäse aus Kuhmilch, Hirtenkäse, mind. 45 % Fett i. Tr.",
    "Brie": "Brie mind. 60 % Fett i. Tr.",
    "Pizzakäse": "Mozzarella mind. 45 % Fett i. Tr.",
    "Schnittkäse": "Schnittkäse mind. 45 % Fett i. Tr.",
    "Blauschimmelkäse": "Edelpilzkäse mind. 50 % Fett i. Tr.",
    "Kondensmilch": "Kondensmilch mind. 8 % Fett, gezuckert",
    "Milchpulver": "Vollmilchpulver",
    "Magermilchpulver": "Magermilchpulver",
    "Süßrahmbutter": "Süßrahmbutter",
    "Kräuterbutter": "Knoblauchbutter/Kräuterbutter",
    "Knoblauchbutter": "Knoblauchbutter/Kräuterbutter",
    "Halbfettmargarine": "Pflanzenmargarine Halbfett, angereichert mit Vitaminen",
    "Rapsölmargarine": "Rapsölmargarine Vollfett, angereichert mit Vitaminen",
    "Sojasahne": "Sojakochcreme",
    "Hafermilch": "Haferdrink ungesüßt",
    "Sojamilch": "Sojadrink ungesüßt",
    "Mandelmilch": "Mandeldrink ungesüßt",
    "Reismilch": "Reisdrink ungesüßt",
    "Kokosdrink": "Kokosmilch/Kokosnussmilch",
    "Kokoscreme": "Kokosmilch/Kokosnussmilch",
    "Sojajoghurt natur": "Soja-Joghurtalternative ungesüßt",
    "Veganer Joghurt": "Soja-Joghurtalternative ungesüßt",
    "pflanzlicher Joghurt": "Soja-Joghurtalternative ungesüßt",
    # Fleisch
    "Suppenhuhn": "Suppenhuhn Fleisch, mit Haut, roh",
    "Suppenhuhn Keule": "Suppenhuhn Schenkel, mit Haut, roh",
    "Brathähnchen": "Hähnchen ganz, entbeint, mit Haut, roh",
    "Poularde": "Hähnchen ganz, entbeint, mit Haut, roh",
    "Hähnchenfleisch": "Hähnchen Fleisch, ohne Haut, roh",
    "Hühnerfleisch": "Hähnchen Fleisch, ohne Haut, roh",
    "Hühnchen": "Hähnchen Fleisch, ohne Haut, roh",
    "Hühnchenbrust": "Hähnchen Brustfilet, roh",
    "Hühnchenbrustfilet": "Hähnchen Brustfilet, roh",
    "Hähnchen Brust ohne Haut": "Hähnchen Brust, ohne Haut, roh",
    "Hähnchenunterschenkel": "Hähnchen Unterschenkel, mit Haut, roh",
    "Hähnchenoberschenkel": "Hähnchen Oberschenkel, mit Haut, roh",
    "Hähnchenstreifen": "Hähnchen Brustfilet, roh",
    "Geflügel": "Hähnchen Fleisch, ohne Haut, roh",
    "Putenbrustfilet": "Pute Brust, ohne Haut, roh",
    "Putenhack": "Pute Fleisch, ohne Haut, roh",
    "Putenhackfleisch": "Pute Fleisch, ohne Haut, roh",
    "Putenkeule": "Pute Keule, ohne Haut, roh",
    "Rindfleisch": "Rind Muskelfleisch, roh",
    "Schweinefleisch": "Schwein Muskelfleisch, roh",
    "Kalbfleisch": "Kalb Muskelfleisch, roh",
    "Lammfleisch": "Lamm Muskelfleisch, roh",
    "Lammkeule": "Schaf Keule, mager, roh",
    "Lammhack": "Lamm Muskelfleisch, roh",
    "Lammkotelett": "Lamm Kotelett, roh",
    "Rinderbraten": "Rind Bratenfleisch (Bug) roh",
    "Schmorbraten": "Rind Bratenfleisch (Bug) roh",
    "Rindersuppenfleisch": "Rind Kochfleisch (Bug) roh",
    "Suppenfleisch": "Rind Kochfleisch (Bug) roh",
    "Rinderrouladen": "Rind Roulade (Oberschale) roh",
    "Rinderhüfte": "Rind Hüfte, roh",
    "Rumpsteak": "Rind Steak (Rücken) roh",
    "Entrecote": "Rind Steak (Rücken) roh",
    "Hüftsteak": "Rind Hüfte, roh",
    "Schweinekotelett": "Schwein Kotelett (Rücken/cranial) roh",
    "Schweinebraten": "Schwein Bratenfleisch (Nuss) roh",
    "Schweineschulter": "Schwein Dünner Bug (ohne Fett und Schwarte) roh",
    "Schweinelachs": "Schwein Lachsbraten, roh",
    "Schweinemedaillons": "Schwein Filetmedaillon, roh",
    "Schweinegeschnetzeltes": "Schwein Schnitzel (Oberschale) roh",
    "Kalbsgeschnetzeltes": "Kalb Schnitzel (Keule) roh",
    "Kalbsfilet": "Kalb Filet/Lende, roh",
    "Mett": "Schwein Hackfleisch, roh",
    "Gehacktes": "Rind/Schwein, Hackfleisch gemischt, roh",
    "Hackfleisch halb und halb": "Rind/Schwein, Hackfleisch gemischt, roh",
    "Rinderhackfleisch mager": "Rind Hackfleisch, roh",
    "Kassler": "Kasseler, Rohpökelware, geräuchert",
    "Kasseler": "Kasseler, Rohpökelware, geräuchert",
    "Schinkenspeck": "Schwein Bauchspeck, Rohpökelware, geräuchert",
    "Bauchspeck": "Schwein Bauchspeck, Rohpökelware, geräuchert",
    "Speckwürfel": "Schwein Bauchspeck, Rohpökelware, geräuchert",
    "Schinkenwurst": "Schinkenwurst roh",
    "Chorizo": "Salami",
    "Cabanossi": "Salami",
    "Pfefferbeißer": "Salami",
    "Leberkäse": "Leberkäse",
    "Würstchen": "Wiener Würstchen",
    "Wiener": "Wiener Würstchen",
    "Frankfurter": "Wiener Würstchen",
    # Fisch
    "Lachssteak": "Lachs roh",
    "Zuchtlachs": "Lachs roh",
    "Wildlachs": "Wildlachs roh",
    "geräucherter Lachs": "Lachs geräuchert (Räucherlachs)",
    "Lachs geräuchert": "Lachs geräuchert (Räucherlachs)",
    "Thunfischsteak": "Thunfisch roh",
    "Thunfisch im eigenen Saft": "Thunfisch im eigenen Saft, Konserve, abgetropft",
    "Thunfisch in Öl": "Thunfisch in Öl, Konserve, abgetropft",
    "Kabeljaufilet": "Dorsch/Kabeljau, roh",
    "Seelachsfilet": "Köhler/Seelachs, roh",
    "Alaska-Seelachs": "Alaska-Pollack/Alaska-Seelachs, roh",
    "Schellfisch": "Schellfisch roh",
    "Heilbutt": "Heilbutt/Weißer Heilbutt, roh",
    "Seehecht": "Seehecht roh",
    "Seeteufel": "Seeteufel roh",
    "Seezunge": "Seezunge roh",
    "Steinbutt": "Steinbutt roh",
    "Sardelle": "Sardelle roh",
    "Sardellenfilet": "Sardelle in Öl, Konserve, abgetropft",
    "Anchovis": "Sardelle in Öl, Konserve, abgetropft",
    "Forellenfilet": "Forelle roh",
    "Lachsforelle": "Meerforelle roh",
    "Karpfen": "Karpfen roh",
    "Scampi": "Garnele/Granat/Krabbe, roh",
    "Shrimps": "Garnele/Granat/Krabbe, roh",
    "Krabben": "Garnele/Granat/Krabbe, roh",
    "Riesengarnele": "Garnele/Granat/Krabbe, roh",
    "Jakobsmuschel": "Pilgermuschel/Jakobsmuschel, roh",
    "Kalmar": "Tintenfisch roh",
    "Calamari": "Tintenfisch roh",
    "Hummer": "Hummer roh",
    "Surimi": "Surimi (Krebsfleischimitat aus Fischmuskeleiweiß geformt)",
    # Hülsenfrüchte, Soja
    "getrocknete Kichererbsen": "Kichererbse reif",
    "Kichererbsenmehl": "Kichererbsenmehl",
    "braune Linsen": "Linse reif",
    "grüne Linsen": "Linse reif",
    "Tellerlinsen": "Linse reif",
    "Berglinsen": "Linse reif",
    "Belugalinsen": "Linse reif",
    "Linsen Dose": "Linse reif, Konserve, abgetropft",
    "Cannellinibohne": "Gartenbohne reif",
    "schwarze Bohne": "Gartenbohne reif",
    "Kidneybohnen getrocknet": "Kidneybohne reif",
    "Limabohne": "Limabohne (Butterbohne Mondbohne) reif",
    "Mungbohne": "Mungbohne reif",
    "Erbsenmehl": "Erbsenmehl",
    "Sojaschnetzel": "Sojaschnetzel/Sojagranulat, texturiert, trocken",
    "Sojagranulat": "Sojaschnetzel/Sojagranulat, texturiert, trocken",
    "Tofu natur": "Tofu",
    "Räuchertofu": "Tofu",
    "Miso": "Miso/Sojabohnenpaste",
    "Misopaste": "Miso/Sojabohnenpaste",
    "Vegane Wiener": "Vegetarische Wiener Würstchen",
    "Hefeflocken": "Hefe Flocken/Nährhefe",
    "Nährhefe": "Hefe Flocken/Nährhefe",
    # Getreide, Nudeln, Brot
    "Haferflocken zart": "Hafer Flocken",
    "Haferflocken kernig": "Hafer Flocken",
    "Porridge": "Hafer Flocken",
    "Hafermehl": "Hafer Mehl",
    "Haferschrot": "Hafer Schrot",
    "Hafergrütze": "Hafer Grütze",
    "Dinkel": "Dinkel ganzes Korn, roh",
    "Weizenvollkornmehl": "Weizen Vollkornmehl",
    "Mehl Type 405": "Weizen Mehl, Type 405",
    "Dinkelmehl Type 630": "Dinkel Mehl, Type 630",
    "Maismehl": "Mais Mehl",
    "Reismehl": "Reis Mehl",
    "Hartweizengrieß": "Hartweizen Grieß",
    "Weichweizengrieß": "Weichweizen Grieß",
    "Wildreis": "Wildreis roh",
    "Milchreis": "Reis poliert, roh",
    "Risottoreis": "Reis poliert, roh",
    "Langkornreis": "Reis poliert, roh",
    "Rundkornreis": "Reis poliert, roh",
    "Parboiled Reis": "Reis poliert, roh",
    "Reisnudeln": "Reisnudeln roh",
    "Glasnudeln": "Glasnudeln aus Mungbohnenstärke, roh",
    "Suppennudeln": "Eierteigwaren roh",
    "Bandnudeln": "Eierteigwaren roh",
    "Tagliatelle": "Eierteigwaren roh",
    "Fettuccine": "Eierteigwaren roh",
    "Spätzle": "Eierteigwaren roh",
    "Lasagneplatten": "Eierteigwaren roh",
    "Nudeln Vollkorn": "Vollkornteigwaren eifrei, roh",
    "Rigatoni": "Teigwaren eifrei, roh",
    "Farfalle": "Teigwaren eifrei, roh",
    "Tortellini": "Eier-Frischteigwaren roh",
    "Ravioli": "Eier-Frischteigwaren roh",
    "Hirseflocken": "Hirse roh",
    "Amaranth": "Amaranth roh",
    "Buchweizen": "Buchweizen roh",
    "Gerste": "Gerste ganzes Korn, roh",
    "Graupen": "Gerste ganzes Korn, roh",
    "Grünkern": "Grünkern ganzes Korn, roh",
    "Toastbrot": "Weizenmischtoastbrot",
    "Toast": "Weizenmischtoastbrot",
    "Baguette": "Weizenbaguette",
    "Semmel": "Weizenbrötchen",
    "Mischbrot": "Roggenmischbrot",
    "Zwieback": "Zwieback eifrei",
    "Cracker": "Cracker",
    "Pita": "Weizenfladenbrot",
    "Naan": "Weizenfladenbrot",
    "Popcornmais": "Mais roh",
    "Maiskörner": "Mais roh",
    "Stärke": "Mais Stärke",
    "Pfeilwurzelmehl": "Pfeilwurzelmehl/Marantastärke",
    "Tapioka": "Tapioka/Tapiokastärke",
    # Backen, Süßes, Aufstriche
    "Vanillinzucker": "Vanillinzucker",
    "Rohrzucker": "Zucker braun (Kandisfarin/Rohzucker)",
    "Rohzucker": "Zucker braun (Kandisfarin/Rohzucker)",
    "Kristallzucker": "Zucker weiß (Raffinadezucker/Weißzucker)",
    "Haushaltszucker": "Zucker weiß (Raffinadezucker/Weißzucker)",
    "Zucker weiß": "Zucker weiß (Raffinadezucker/Weißzucker)",
    "Xylit": "Xylit Pulver (E 967)",
    "Birkenzucker": "Xylit Pulver (E 967)",
    "Melasse": "Melasse",
    "Apfeldicksaft": "Apfeldicksaft",
    "Hirschhornsalz": "Hirschhornsalz (Ammoniumhydrogencarbonat, E 503)",
    "Backhefe": "Backhefe frisch (Frischbackhefe)",
    "Hefewürfel": "Backhefe frisch (Frischbackhefe)",
    "Trockenhefe Päckchen": "Backhefe getrocknet (Trockenbackhefe)",
    "Gelatine Blätter": "Gelatine/Speisegelatine",
    "Sahnesteif": "Sahnestandmittel",
    "Puddingpulver": "Puddingpulver Vanille, ungezuckert",
    "Backkakao": "Kakaopulver stark entölt",
    "Orangeat": "Orangeat",
    "Zitronat": "Zitronat/Sukkade",
    "Nutella": "Nuss-Nougat-Creme",
    "Marzipan": "Marzipan",
    # Würzmittel, Brühe
    "Kräutersalz": "Gewürzsalz/Kräutersalz",
    "Gewürzsalz": "Gewürzsalz/Kräutersalz",
    "Steinsalz": "Steinsalz",
    "Zitronensäure": "Citronensäure/Zitronensäure (E 330)",
    "Reisessig": "Weinessig",
    "Weißweinessig": "Weinessig",
    "Rotweinessig": "Weinessig",
    "Kräuteressig": "Kräuteressig",
    "Branntweinessig": "Branntweinessig",
    "Balsamicoessig": "Balsamicoessig",
    "Aceto Balsamico": "Balsamicoessig",
    "Dijonsenf": "Senf mittelscharf",
    "Senf mittelscharf": "Senf mittelscharf",
    "scharfer Senf": "Senf scharf",
    "süßer Senf": "Senf süß",
    "Sojasoße": "Sojasauce/Sojasoße",
    "Tamari": "Sojasauce/Sojasoße",
    "Remoulade": "Remoulade (Fertigprodukt)",
    "Pesto": "Pesto verde",
    "Pesto rosso": "Pesto rosso",
    "Sambal": "Sambal Oelek, Würzpaste",
    "Mayo": "Mayonnaise (Fertigprodukt)",
    "Salatmayonnaise": "Feinkostsauce/Grillsauce, Mayonnaise-Basis",
    "Fischbrühe": "Fischbrühe",
    "Fischfond": "Fischbrühe",
    "Gemüsefond": "Gemüsebrühe",
    "Hühnerfond": "Hühnerbrühe",
    "Geflügelbrühe": "Hühnerbrühe",
    "Rinderbrühe": "Fleischbrühe (Rind)",
    "Fleischbrühe": "Fleischbrühe (Rind)",
    "Rinderkraftbrühe": "Rinderkraftbrühe",
    "Rinderfond": "Fleischbrühe (Rind)",
    "Kalbsbrühe": "Kalbsbrühe",
    "Brühwürfel": "Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Gemüsebrühwürfel": "Gemüse Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Gemüsebrühepulver": "Gemüse Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Gemüsebrühe Instant": "Gemüse Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Hühnerbrühwürfel": "Hühner Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Hühnerbrühepulver": "Hühner Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Fleischbrühwürfel": "Fleisch Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Rinderbrühwürfel": "Fleisch Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Instantbrühe": "Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Brühpulver": "Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Bouillon": "Bouillon/Brühe/Suppe (Brühwürfel, Pulver)",
    "Pfeffer schwarz": "Pfeffer schwarz, getrocknet",
    "schwarzer Pfeffer": "Pfeffer schwarz, getrocknet",
    "Pfefferkörner": "Pfeffer schwarz, getrocknet",
    "Salz und Pfeffer": "Speisesalz/Siedesalz/Tafelsalz",
    # Frische Kräuter ohne BLS-Eintrag: Näherung auf Petersilienblatt (kleine Mengen)
    "Dill": "Petersilienblatt roh",
    "Koriander": "Petersilienblatt roh",
    "Korianderblätter": "Petersilienblatt roh",
    "Koriandergrün": "Petersilienblatt roh",
    "Minze": "Petersilienblatt roh",
    "Pfefferminze": "Petersilienblatt roh",
    "Kerbel": "Petersilienblatt roh",
    "Estragon": "Petersilienblatt roh",
    "Liebstöckel": "Petersilienblatt roh",
    "Zitronenmelisse": "Petersilienblatt roh",
    "Bohnenkraut": "Petersilienblatt roh",
    # Sammelbegriff Kräuter (Näherung: Petersilie bzw. getrocknetes Basilikum)
    "Kräuter": "Petersilienblatt roh",
    "gemischte Kräuter": "Petersilienblatt roh",
    "Kräutermischung": "Petersilienblatt roh",
    "Küchenkräuter": "Petersilienblatt roh",
    "italienische Kräuter": "Basilikum getrocknet",
    "Kräuter der Provence": "Basilikum getrocknet",
    "getrocknete Kräuter": "Basilikum getrocknet",
    # Getränke
    "Espresso": "Kaffee (Getränk)",
    "Gemüsesaft": "Gemüsesaft aus Gemüsemischung",
    "Traubensaft": "Traubensaft",
    "Ananassaft": "Ananassaft",
    "Weißwein": "Weißwein trocken",
    "Rotwein": "Rotwein trocken",
    "Bier": "Pilsner Bier",
}


def _build_seed(raw: dict[str, str]) -> dict[str, str]:
    seed: dict[str, str] = {}
    for alias, target in raw.items():
        key = normalize_name(alias)
        if not key:
            raise ValueError(f"Alias ergibt nach der Normalisierung nichts: {alias!r}")
        if key in seed and seed[key] != target:
            raise ValueError(f"Alias {alias!r} kollidiert mit einem anderen Ziel: {key!r}")
        seed[key] = target
    return seed


# Normalisierter Alias -> vollständiger BLS-Name (Zutat im Katalog)
SYNONYM_SEED: dict[str, str] = _build_seed(_RAW_SEED)
