"""phase1 schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 12:14:40.500162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_person_token_hash'), 'person', ['token_hash'], unique=False)
    op.create_table('goal_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('rate_kg_per_week', sa.Float(), nullable=True),
    sa.Column('kcal_modifier_pct', sa.Float(), nullable=True),
    sa.Column('protein_g_per_kg', sa.Float(), nullable=True),
    sa.Column('fat_pct', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_profile_person_valid', 'goal_profile', ['person_id', 'valid_from'], unique=False)
    op.create_table('health_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('lean_mass_kg', sa.Float(), nullable=True),
    sa.Column('active_kcal', sa.Float(), nullable=True),
    sa.Column('basal_kcal', sa.Float(), nullable=True),
    sa.Column('steps', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('sleep_h', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'day', 'source', name='uq_health_daily_person_day_source')
    )
    op.create_index('ix_health_daily_person_day', 'health_daily', ['person_id', 'day'], unique=False)
    op.create_table('import_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_job_person_id'), 'import_job', ['person_id'], unique=False)
    op.create_table('lab_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sa.String(length=120), nullable=True),
    sa.Column('order_no', sa.String(length=40), nullable=True),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('sample_datetime', sa.DateTime(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'order_no', name='uq_lab_report_person_order')
    )
    op.create_table('lab_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('analyte', sa.String(length=120), nullable=False),
    sa.Column('comparator', sa.String(length=10), nullable=False),
    sa.Column('threshold_low', sa.Float(), nullable=True),
    sa.Column('threshold_high', sa.Float(), nullable=True),
    sa.Column('effect_key', sa.String(length=60), nullable=False),
    sa.Column('effect_weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('doctor_confirmed', sa.Boolean(), nullable=False),
    sa.Column('suggested_by_app', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_rule_person_id'), 'lab_rule', ['person_id'], unique=False)
    op.create_table('nutrient_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('per', sa.String(length=10), nullable=False),
    sa.Column('hard', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('doctor_confirmed', sa.Boolean(), nullable=False),
    sa.Column('suggested_by_app', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrient_rule_person_id'), 'nutrient_rule', ['person_id'], unique=False)
    op.create_table('person_settings',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('supplement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dose_amount', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.String(length=20), nullable=True),
    sa.Column('nutrients_per_day', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('taking', sa.Boolean(), nullable=False),
    sa.Column('time_of_day', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_person_id'), 'supplement', ['person_id'], unique=False)
    op.create_table('training_plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=60), nullable=False),
    sa.Column('intensity', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('expected_kcal', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_plan_person_weekday', 'training_plan_item', ['person_id', 'weekday'], unique=False)
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('active_kcal', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'start', 'type', 'source', name='uq_workout_person_start_type_source')
    )
    op.create_index('ix_workout_person_start', 'workout', ['person_id', 'start'], unique=False)
    op.create_table('lab_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('analyte', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_op', sa.String(length=2), nullable=True),
    sa.Column('flag', sa.String(length=1), nullable=True),
    sa.Column('ref_low', sa.Float(), nullable=True),
    sa.Column('ref_high', sa.Float(), nullable=True),
    sa.Column('ref_op', sa.String(length=2), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('material', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['lab_report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'analyte', 'unit', name='uq_lab_result_report_analyte_unit')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_result')
    op.drop_index('ix_workout_person_start', table_name='workout')
    op.drop_table('workout')
    op.drop_index('ix_training_plan_person_weekday', table_name='training_plan_item')
    op.drop_table('training_plan_item')
    op.drop_index(op.f('ix_supplement_person_id'), table_name='supplement')
    op.drop_table('supplement')
    op.drop_table('person_settings')
    op.drop_index(op.f('ix_nutrient_rule_person_id'), table_name='nutrient_rule')
    op.drop_table('nutrient_rule')
    op.drop_index(op.f('ix_lab_rule_person_id'), table_name='lab_rule')
    op.drop_table('lab_rule')
    op.drop_table('lab_report')
    op.drop_index(op.f('ix_import_job_person_id'), table_name='import_job')
    op.drop_table('import_job')
    op.drop_index('ix_health_daily_person_day', table_name='health_daily')
    op.drop_table('health_daily')
    op.drop_index('ix_goal_profile_person_valid', table_name='goal_profile')
    op.drop_table('goal_profile')
    op.drop_index(op.f('ix_person_token_hash'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
