"""phase2 recipes

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 08:24:39.564880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('source_code', sa.String(length=40), nullable=True),
    sa.Column('kcal_100', sa.Float(), nullable=True),
    sa.Column('protein_100', sa.Float(), nullable=True),
    sa.Column('fat_100', sa.Float(), nullable=True),
    sa.Column('carb_100', sa.Float(), nullable=True),
    sa.Column('fiber_100', sa.Float(), nullable=True),
    sa.Column('salt_100', sa.Float(), nullable=True),
    sa.Column('micros', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('density_g_per_ml', sa.Float(), nullable=True),
    sa.Column('piece_g', sa.Float(), nullable=True),
    sa.Column('is_fish', sa.Boolean(), nullable=False),
    sa.Column('is_potassium_salt', sa.Boolean(), nullable=False),
    sa.Column('shelf_days', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_code', name='uq_ingredient_source_code')
    )
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=False)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_site', sa.String(length=120), nullable=True),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('prep_min', sa.Integer(), nullable=True),
    sa.Column('cook_min', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('min_g', sa.Float(), nullable=False),
    sa.Column('max_g', sa.Float(), nullable=False),
    sa.Column('step_g', sa.Float(), nullable=False),
    sa.Column('typical_g', sa.Float(), nullable=True),
    sa.Column('weekend_fixed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_preference',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'ingredient_id')
    )
    op.create_table('ingredient_synonym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_ingredient_synonym_ingredient_id'), 'ingredient_synonym', ['ingredient_id'], unique=False)
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('grams', sa.Float(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredient_ingredient_id'), 'recipe_ingredient', ['ingredient_id'], unique=False)
    op.create_index('ix_recipe_ingredient_recipe', 'recipe_ingredient', ['recipe_id', 'position'], unique=False)
    op.create_table('recipe_rating',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'person_id')
    )
    op.create_table('recipe_tag',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('slot_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cuisine', sa.String(length=60), nullable=True),
    sa.Column('main_ingredient', sa.String(length=80), nullable=True),
    sa.Column('batch_cookable', sa.Boolean(), nullable=False),
    sa.Column('transportable', sa.Boolean(), nullable=False),
    sa.Column('warm', sa.Boolean(), nullable=False),
    sa.Column('shelf_days', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('component_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('grams_per_unit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_variant_component_id'), 'component_variant', ['component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_component_variant_component_id'), table_name='component_variant')
    op.drop_table('component_variant')
    op.drop_table('recipe_tag')
    op.drop_table('recipe_rating')
    op.drop_index('ix_recipe_ingredient_recipe', table_name='recipe_ingredient')
    op.drop_index(op.f('ix_recipe_ingredient_ingredient_id'), table_name='recipe_ingredient')
    op.drop_table('recipe_ingredient')
    op.drop_index(op.f('ix_ingredient_synonym_ingredient_id'), table_name='ingredient_synonym')
    op.drop_table('ingredient_synonym')
    op.drop_table('ingredient_preference')
    op.drop_table('component')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
